### ISSUE TITLE
No able to run the project

### ISSUE THREAD

**Issue by felipecpc** [serhatsezer/MedReminder#1]
I tried to run the project but ir failing with this error:

![screen shot 2017-07-17 at 14 56 46](https://user-images.githubusercontent.com/698459/28268938-7b3e17a8-6b00-11e7-94e2-1a919cab658b.png)

Could you please take a look?

**Comment by serhatsezer** [comment]
Hey @felipecpc, Could you please try this https://github.com/facebook/react-native/issues/14246#issuecomment-304742305, 

If same error still occur, please terminate all windows which you used when you try to run project doing by pressing cmd + c (stop running terminal associated with react native project) after then run "npm start" open new terminal and go project directory and run react-native run-ios.

**Comment by felipecpc** [comment]
Actually I managed to run it using expo.io 

Thanks
